//! Aridad real de los builtins (v0.6.29): `(nombre, mínimo, máximo)`, con `None` para
//! los genuinamente variádicos (`print`, `max`, …). La consulta `check_call_arity` en cada
//! llamada del fuente: un argumento de más es error en vez de ignorarse en silencio.
//!
//! Entra acá todo builtin registrado con `param_count = -1` (el anti-rot lo exige) y todo
//! builtin de aridad fija que además acepta opcionales. Los de aridad fija exacta no hace
//! falta listarlos: su `param_count` ya es la verdad.

/// Argumentos SÓLO por nombre de builtins que además aceptan posicionales (v0.6.29, DATOS-4):
/// `sum(m, axis = 0)`, `std(xs, ddof = 0)`. No cuentan para la aridad posicional. El builtin
/// los lee con `Interpreter::kwarg`.
pub const BUILTIN_KWARGS: &[(&str, &[&str])] = &[
    ("sum", &["axis"]),
    ("product", &["axis"]),
    ("mean", &["axis"]),
    ("min", &["axis"]),
    ("max", &["axis"]),
    ("median", &["axis"]),
    ("percentile", &["axis"]),
    ("quantile", &["axis"]),
    ("std", &["axis", "ddof"]),
    ("var", &["axis", "ddof"]),
    ("argmin", &["axis"]),
    ("argmax", &["axis"]),
    ("cumsum", &["axis"]),
    ("diff", &["axis"]),
    ("concat", &["axis"]),
    ("stack", &["axis"]),
    ("cov", &["ddof"]),
    ("random_normal", &["mean", "std"]),
];

pub fn kwargs_of(name: &str) -> &'static [&'static str] {
    BUILTIN_KWARGS.iter().find(|(n, _)| *n == name).map(|(_, k)| *k).unwrap_or(&[])
}

pub const BUILTIN_ARITY: &[(&str, usize, Option<usize>)] = &[
    ("random", 0, Some(1)),
    ("random_int", 2, Some(3)),
    ("parquet_write", 1, Some(2)),
    ("sum", 1, Some(2)),
    ("product", 1, Some(2)),
    ("mean", 1, Some(2)),
    ("min", 1, None),
    ("max", 1, None),
    ("median", 1, Some(2)),
    ("percentile", 2, Some(3)),
    ("quantile", 2, Some(3)),
    ("std", 1, Some(2)),
    ("var", 1, Some(2)),
    ("date", 1, Some(3)),
    ("datetime", 1, Some(7)),
    ("parse_date", 1, Some(2)),
    ("parse_datetime", 1, Some(3)),
    ("date_range", 2, Some(3)),
    ("jsonl_decode", 1, Some(2)),
    ("drop_missing", 1, Some(2)),
    ("count_by", 1, Some(2)),
    ("join", 2, Some(4)),
    ("pivot", 4, Some(5)),
    ("hmac", 2, Some(3)),
    ("evm_nonce", 2, Some(3)),
    ("solana_tx", 1, Some(2)),
    ("algorand_tx", 1, Some(2)),
    ("abi_decode_log", 2, Some(3)),
    ("sort", 1, Some(2)),
    ("sort_by", 2, Some(3)),
    ("get", 2, Some(3)),
    ("merge", 1, None),
    ("abi_decode", 2, Some(3)),
    ("add_rule", 3, Some(4)),
    ("aes_gcm_decrypt", 3, Some(5)),
    ("aes_gcm_encrypt", 3, Some(4)),
    ("agent_stop", 1, Some(2)),
    ("agents", 0, Some(0)),
    ("algorand_account", 2, Some(3)),
    ("algorand_mnemonic", 1, Some(1)),
    ("algorand_mnemonic_to_key", 1, Some(2)),
    ("algorand_params", 1, Some(2)),
    ("algorand_send", 2, Some(3)),
    ("algorand_wait", 2, Some(4)),
    ("append_file", 2, Some(2)),
    ("arange", 2, Some(3)),
    ("as_secret", 1, Some(2)),
    ("assert", 1, Some(2)),
    ("assert_eq", 2, Some(3)),
    ("assert_ne", 2, Some(3)),
    ("attest", 0, Some(1)),
    ("bech32_decode", 1, Some(2)),
    ("bech32_encode", 2, Some(3)),
    ("binary", 1, Some(3)),
    ("btc_address", 1, Some(3)),
    ("btc_rpc", 2, Some(4)),
    ("btc_wait", 2, Some(4)),
    ("bus_publish", 1, Some(2)),
    ("bus_recv", 1, Some(2)),
    ("bus_subscribe", 1, Some(2)),
    ("bus_topics", 0, Some(0)),
    ("bus_unsubscribe", 1, Some(1)),
    ("bytes", 1, Some(2)),
    ("captoken_allows", 2, Some(3)),
    ("captoken_attenuate", 2, Some(3)),
    ("captoken_mint", 2, Some(3)),
    ("captoken_verify", 2, Some(3)),
    ("chart", 2, Some(3)),
    ("chart_svg", 2, Some(3)),
    ("check_rules", 0, Some(2)),
    ("clear_cookie", 2, Some(3)),
    ("code", 1, Some(2)),
    ("complete_step", 2, Some(3)),
    ("content", 0, Some(1)),
    ("create_progress", 1, Some(2)),
    ("created", 0, Some(1)),
    ("cron_after", 2, Some(2)),
    ("cron_cancel", 1, Some(1)),
    ("cron_every", 2, Some(3)),
    ("cron_list", 0, Some(0)),
    ("cron_status", 0, Some(0)),
    ("csv_encode", 1, Some(2)),
    ("csv_parse", 1, Some(2)),
    ("cwd", 0, Some(0)),
    ("db_close", 0, Some(1)),
    ("db_open", 1, Some(2)),
    ("decimal", 1, Some(2)),
    ("declassify", 2, Some(3)),
    ("decode", 1, Some(2)),
    ("delete_dir", 1, Some(2)),
    ("delete_file", 1, Some(1)),
    ("did_key_encode", 1, Some(2)),
    ("document_sign", 2, Some(3)),
    ("document_verify", 2, Some(3)),
    ("ecdh_keypair", 1, Some(1)),
    ("ecdh_shared_secret", 3, Some(3)),
    ("ecdsa_p256_sign", 2, Some(2)),
    ("ecdsa_p256_verify", 3, Some(3)),
    ("edit_file", 3, Some(4)),
    ("env", 1, Some(2)),
    ("evm_balance", 2, Some(3)),
    ("evm_call", 2, Some(3)),
    ("evm_fee_history", 1, Some(3)),
    ("evm_rpc", 2, Some(3)),
    ("evm_wait", 2, Some(4)),
    ("fail", 0, Some(2)),
    ("fail_step", 2, Some(3)),
    ("fetch", 1, Some(5)),
    ("float", 1, Some(2)),
    ("fmt", 1, Some(2)),
    ("format_time", 1, Some(2)),
    ("get_rules", 0, Some(1)),
    ("grep", 2, Some(3)),
    ("hd_derive", 2, Some(4)),
    ("histogram", 1, Some(2)),
    ("hkdf_sha256", 4, Some(4)),
    ("http", 2, Some(6)),
    ("http_bytes", 2, Some(6)),
    ("http_delete", 1, Some(3)),
    ("http_get", 1, Some(4)),
    ("http_post", 1, Some(4)),
    ("http_put", 1, Some(4)),
    ("http_sign", 2, Some(3)),
    ("http_signature_verify", 2, Some(3)),
    ("image", 1, Some(2)),
    ("int", 1, Some(2)),
    ("int_to_bytes", 1, Some(2)),
    ("json_decode", 1, Some(2)),
    ("jwt_sign", 2, Some(3)),
    ("jwt_verify", 2, Some(3)),
    ("keystore_export", 2, Some(3)),
    ("keystore_import", 2, Some(3)),
    ("llm_step", 1, Some(3)),
    ("mnemonic_from_entropy", 1, Some(2)),
    ("mnemonic_generate", 0, Some(2)),
    ("mnemonic_to_entropy", 1, Some(1)),
    ("mnemonic_to_seed", 1, Some(2)),
    ("mongo_aggregate", 2, Some(2)),
    ("mongo_collections", 0, Some(0)),
    ("mongo_count", 1, Some(2)),
    ("mongo_delete", 1, Some(2)),
    ("mongo_find", 1, Some(3)),
    ("mongo_find_one", 1, Some(2)),
    ("mongo_insert", 2, Some(2)),
    ("mongo_insert_many", 2, Some(2)),
    ("mongo_update", 3, Some(3)),
    ("mtls_identity", 2, Some(3)),
    ("norm", 1, Some(2)),
    ("not_found", 0, Some(1)),
    ("number", 1, Some(2)),
    ("oidc_verify", 2, Some(2)),
    ("ok", 0, Some(1)),
    ("page", 1, Some(2)),
    ("paged", 1, Some(2)),
    ("parallel_map", 2, Some(3)),
    ("parse_time", 1, Some(2)),
    ("platform", 0, Some(0)),
    ("print", 0, None),
    ("private", 2, Some(2)),
    ("proc_close", 1, Some(1)),
    ("proc_close_stdin", 1, Some(1)),
    ("proc_kill", 1, Some(2)),
    ("proc_recv", 1, Some(2)),
    ("proc_resize", 3, Some(3)),
    ("proc_select", 1, Some(2)),
    ("proc_send", 2, Some(2)),
    ("proc_spawn", 1, Some(3)),
    ("proc_stats", 1, Some(1)),
    ("proc_status", 1, Some(1)),
    ("proc_wait", 1, Some(2)),
    ("psbt_decode", 1, Some(2)),
    ("push_send", 2, Some(3)),
    ("push_vapid_keys", 0, Some(0)),
    ("raise", 1, Some(1)),
    ("range", 1, Some(3)),
    ("read_file", 1, Some(3)),
    ("read_line", 0, Some(1)),
    ("recall", 0, Some(6)),
    ("receipt", 0, Some(1)),
    ("receipt_verify", 2, Some(3)),
    ("redirect", 1, Some(2)),
    ("redis_decr", 1, Some(1)),
    ("redis_del", 1, None),
    ("redis_exists", 1, None),
    ("redis_expire", 2, Some(2)),
    ("redis_get", 1, Some(1)),
    ("redis_hdel", 2, None),
    ("redis_hget", 2, Some(2)),
    ("redis_hgetall", 1, Some(1)),
    ("redis_hincrby", 3, Some(3)),
    ("redis_hset", 2, Some(2)),
    ("redis_incr", 1, Some(1)),
    ("redis_incrby", 2, Some(2)),
    ("redis_keys", 1, Some(1)),
    ("redis_llen", 1, Some(1)),
    ("redis_lock", 1, Some(2)),
    ("redis_lpop", 1, Some(1)),
    ("redis_lpush", 2, None),
    ("redis_lrange", 3, Some(3)),
    ("redis_mget", 1, Some(1)),
    ("redis_mset", 1, Some(1)),
    ("redis_persist", 1, Some(1)),
    ("redis_rpop", 1, Some(1)),
    ("redis_rpush", 2, None),
    ("redis_sadd", 2, None),
    ("redis_set", 2, Some(3)),
    ("redis_sismember", 2, Some(2)),
    ("redis_smembers", 1, Some(1)),
    ("redis_srem", 2, None),
    ("redis_ttl", 1, Some(1)),
    ("redis_type", 1, Some(1)),
    ("redis_unlock", 2, Some(2)),
    ("reduce", 2, Some(3)),
    ("remember", 2, Some(3)),
    ("render", 0, Some(2)),
    ("respond", 1, Some(3)),
    ("rlp_decode", 1, Some(2)),
    ("rsa_sign_sha256", 2, Some(2)),
    ("rsa_verify_sha256", 3, Some(3)),
    ("run", 1, Some(4)),
    ("run_program", 1, Some(2)),
    ("schnorr_sign", 2, Some(3)),
    ("secp256k1_pubkey", 1, Some(2)),
    ("secret", 1, Some(2)),
    ("select", 1, Some(2)),
    ("self_path", 0, Some(0)),
    ("set_cookie", 3, Some(4)),
    ("shutdown", 0, Some(1)),
    ("sleep", 0, Some(1)),
    ("slice", 1, Some(3)),
    ("solana_wait", 2, Some(3)),
    ("solana_rpc", 2, Some(3)),
    ("spend_total", 1, Some(2)),
    ("spl_ata", 2, Some(3)),
    ("spl_balance", 3, Some(4)),
    ("sql", 1, Some(2)),
    ("sql_batch", 1, Some(2)),
    ("sql_exec", 1, Some(2)),
    ("sql_tables", 0, Some(0)),
    ("state_get", 1, Some(2)),
    ("state_incr", 1, Some(2)),
    ("state_set", 1, Some(2)),
    ("svg_to_pdf", 1, Some(2)),
    ("svg_to_png", 1, Some(2)),
    ("tar_create", 1, Some(2)),
    ("tar_extract", 2, Some(3)),
    ("term_close", 1, Some(1)),
    ("term_open", 0, Some(1)),
    ("term_recv", 1, Some(2)),
    ("term_size", 1, Some(1)),
    ("term_stats", 1, Some(1)),
    ("term_write", 1, Some(2)),
    ("token", 0, Some(1)),
    ("toml_parse", 1, Some(2)),
    ("totp", 1, Some(2)),
    ("totp_verify", 2, Some(3)),
    ("transform", 2, Some(3)),
    ("verify_hmac", 3, Some(4)),
    ("watch", 1, Some(2)),
    ("watch_close", 1, Some(1)),
    ("watch_recv", 1, Some(2)),
    ("watch_stats", 1, Some(1)),
    ("wif_import", 1, Some(2)),
    ("write_file", 2, Some(2)),
    ("ws_broadcast", 2, Some(2)),
    ("ws_close", 1, Some(1)),
    ("ws_connect", 1, Some(3)),
    ("ws_recv", 1, Some(2)),
    ("ws_select", 1, Some(2)),
    ("ws_select_all", 1, Some(2)),
    ("ws_send", 2, Some(2)),
    ("ws_stats", 1, Some(1)),
    ("ws_status", 1, Some(1)),
    ("zip_create", 1, Some(2)),
    ("zip_extract", 2, Some(3)),
];
